### ISSUE TITLE
Will this work with the motherboard Intel graphics ?

### ISSUE THREAD

**Issue by AaronNGray** [TeksuSiK/hackintosh#3]
Will this work with the motherboard Intel graphics ?

**Comment by TeksuSiK** [comment]
Did you mean integraded Intel graphics card? Some modifications will be required. You can find more [here](https://dortania.github.io/OpenCore-Install-Guide/config.plist/kaby-lake.html#deviceproperties)

**Comment by AaronNGray** [comment]
@TeksuSiK Is there a plist I can download anywhere. People keep on saying the ASUS Z270-A is simple but I cannot grok the settings without spending a lot of time to try and get to understand them.

**Comment by TeksuSiK** [comment]
Everything could be found in this repo, take a careful look at readme
